"""@deprecated — re-export only. Use massive.core.empirical_calibration directly."""

from massive.core.empirical_calibration import (  # noqa: F401
    ALPHA_BLEND_MAX,
    ALPHA_BLEND_MIN,
    COMPETENCIA_PESO_MAX,
    COMPETENCIA_PESO_MIN,
    EFECTO_VECINOS_MAX,
    EFECTO_VECINOS_MIN,
    ENGINE_METADATA_KEYS,
    HK_EPSILON_MAX,
    HK_EPSILON_MIN,
    HOMOFILIA_TASA_MAX,
    HOMOFILIA_TASA_MIN,
    MASSIVE_EMPIRICAL_MASTER,
    MASSIVE_RUNTIME_PARAMS,
    RUIDO_BASE_MAX,
    RUIDO_BASE_MIN,
    RUIDO_DESCONFIANZA_MAX,
    RUIDO_DESCONFIANZA_MIN,
    STRATEGIC_WEIGHT_MAX,
    STRATEGIC_WEIGHT_MIN,
    TIPPING_POINT_MEAN,
    TIPPING_POINT_STD,
    apply_empirical_profile,
    build_empirical_engine_config,
    export_to_json,
)

__all__ = [
    "ALPHA_BLEND_MAX",
    "ALPHA_BLEND_MIN",
    "COMPETENCIA_PESO_MAX",
    "COMPETENCIA_PESO_MIN",
    "EFECTO_VECINOS_MAX",
    "EFECTO_VECINOS_MIN",
    "ENGINE_METADATA_KEYS",
    "HK_EPSILON_MAX",
    "HK_EPSILON_MIN",
    "HOMOFILIA_TASA_MAX",
    "HOMOFILIA_TASA_MIN",
    "MASSIVE_EMPIRICAL_MASTER",
    "MASSIVE_RUNTIME_PARAMS",
    "RUIDO_BASE_MAX",
    "RUIDO_BASE_MIN",
    "RUIDO_DESCONFIANZA_MAX",
    "RUIDO_DESCONFIANZA_MIN",
    "STRATEGIC_WEIGHT_MAX",
    "STRATEGIC_WEIGHT_MIN",
    "TIPPING_POINT_MEAN",
    "TIPPING_POINT_STD",
    "apply_empirical_profile",
    "build_empirical_engine_config",
    "export_to_json",
]
