SOURCES = [
    # ── Episodios políticos con datos confirmados ──
    {"id": "02_trump", "episode": "Trump Approval", "source": "FiveThirtyEight", "format": "csv",
     "url": "", "scenario_macro": "E1", "scenario_micro": "F1", "metric": "complement",
     "date_range": "2017-01-20 to 2021-01-20", "sample_size": "1500-5000",
     "notes": "Promedio multi-encuestadora (datahub.io mirror)"},
    {"id": "04_chile_plebiscito", "episode": "Chile Plebiscite", "source": "CADEM", "format": "csv",
     "url": "", "scenario_macro": "E3", "scenario_micro": "F3", "metric": "complement",
     "date_range": "2020", "sample_size": "1000",
     "notes": "Compilado desde CADEM Plaza Pública + resultado oficial"},
    {"id": "06_mexico", "episode": "Mexico Elections 2018", "source": "Parametría/Grok", "format": "csv",
     "url": "", "scenario_macro": "E4", "scenario_micro": "F1", "metric": "bernoulli",
     "date_range": "2018", "sample_size": "~50000",
     "notes": "Datos Grok desde Twitter/X + promedios encuestadoras"},
    {"id": "09_france_gilets", "episode": "France Yellow Vests", "source": "BVA-Odoxa", "format": "csv",
     "url": "", "scenario_macro": "E6", "scenario_micro": "F4", "metric": "complement",
     "date_range": "2018-2019", "sample_size": "1000-1200",
     "notes": "Compilado desde Wikipedia tabla de sondeos BVA/Elabe/Harris"},
    {"id": "12_brazil", "episode": "Brazil Elections 2018", "source": "Datafolha/Grok", "format": "csv",
     "url": "", "scenario_macro": "E4", "scenario_micro": "F1", "metric": "bernoulli",
     "date_range": "2018", "sample_size": "~50000",
     "notes": "Datos Grok desde Twitter/X + Datafolha"},

    # ── Episodios corporativos (reemplazan políticos difíciles) ──
    {"id": "c01_glassdoor_sat", "episode": "Employee Satisfaction 2021-2023", "source": "Glassdoor",
     "format": "csv", "url": "", "scenario_macro": "E1", "scenario_micro": "F1", "metric": "complement",
     "date_range": "2021-01 to 2023-12", "sample_size": "10-65/mes",
     "notes": "Agregación mensual reviews Glassdoor overall rating >=3 = support (Bright Data sample)"},
    {"id": "c02_ns_engagement", "episode": "Public Sector Engagement", "source": "Nova Scotia Gov",
     "format": "csv", "url": "https://data.novascotia.ca/api/views/m5ke-g2xy/rows.csv", "scenario_macro": "E1",
     "scenario_micro": "F1", "metric": "complement", "date_range": "2019 to 2024", "sample_size": "~4000 gov employees",
     "notes": "Nova Scotia 'How's Work Going' Employee Engagement Survey"},
    {"id": "c03_tech_layoffs", "episode": "Tech Layoffs 2022-2023", "source": "Layoffs.fyi / Blind",
     "format": "csv", "url": "", "scenario_macro": "E6", "scenario_micro": "F4", "metric": "complement",
     "date_range": "2022-11 to 2023-06", "sample_size": "~260k laid off",
     "notes": "Sintético realista basado en layoffs.fyi: Meta 21k, Google 12k, Amazon 27k, Microsoft 10k, Twitter 7k"},
    {"id": "c04_rto_conflict", "episode": "Return-to-Office Mandates 2023", "source": "Multiple (WSJ, Blind, Gartner)",
     "format": "csv", "url": "", "scenario_macro": "E2", "scenario_micro": "F2", "metric": "complement",
     "date_range": "2023-01 to 2023-12", "sample_size": "N/A",
     "notes": "Sintético realista basado en RTO mandates: Amazon 3-day, Disney 4-day, Starbucks, Apple, Google, Goldman Sachs"},
    {"id": "c05_great_resignation", "episode": "Great Resignation Wave", "source": "BLS / Microsoft WorkTrendIndex",
     "format": "csv", "url": "", "scenario_macro": "E2", "scenario_micro": "F4", "metric": "complement",
     "date_range": "2021-03 to 2022-12", "sample_size": "BLS quit rate 2.8-3.0%",
     "notes": "Sintético realista basado en BLS quit rate records y Microsoft 2022 WorkTrendIndex: 53% more likely to quit"},
    {"id": "c06_digital_transformation", "episode": "Digital Acceleration 2020-2022",
     "source": "McKinsey / BCG", "format": "csv", "url": "", "scenario_macro": "E4", "scenario_micro": "F1",
     "metric": "bernoulli", "date_range": "2020-03 to 2022-12", "sample_size": "N/A",
     "notes": "Sintético realista basado en McKinsey: 7-year digital adoption compressed into months (COVID catalyst)"},
    {"id": "c07_dei_adoption", "episode": "DEI Program Adoption 2020-2024", "source": "LinkedIn / Glassdoor",
     "format": "csv", "url": "", "scenario_macro": "E5", "scenario_micro": "F1", "metric": "complement",
     "date_range": "2020-06 to 2024-06", "sample_size": "N/A",
     "notes": "Sintético realista basado en LinkedIn DEI hiring trends 2020-2024 + Glassdoor diversity ratings"},
    {"id": "c08_ceo_approval", "episode": "CEO Approval Divide", "source": "Glassdoor CEO Ratings",
     "format": "csv", "url": "", "scenario_macro": "E2", "scenario_micro": "F2", "metric": "complement",
     "date_range": "2021 to 2023", "sample_size": "N/A",
     "notes": "Sintético realista basado en Glassdoor CEO approval ratings por industria (tech vs finance vs retail)"},
    {"id": "c09_burnout", "episode": "Employee Burnout Crisis 2021-2022", "source": "Deloitte / APA",
     "format": "csv", "url": "", "scenario_macro": "E2", "scenario_micro": "F4", "metric": "complement",
     "date_range": "2021-01 to 2022-12", "sample_size": "Deloitte n=1000",
     "notes": "Sintético realista basado en Deloitte 2022: 77% experienced burnout, 46% say worse than prev year"},
    {"id": "c10_ai_anxiety", "episode": "AI Workplace Anxiety 2023-2024", "source": "McKinsey / Pew",
     "format": "csv", "url": "", "scenario_macro": "E5", "scenario_micro": "F2", "metric": "complement",
     "date_range": "2023-01 to 2024-06", "sample_size": "McKinsey n=~3000",
     "notes": "Sintético realista basado en McKinsey 2023: 25% job tasks exposed to GenAI, Pew 2024: 52% worried"},
]


def get_source_config(episode_id):
    for s in SOURCES:
        if s["id"] == episode_id or s["episode"].lower() == episode_id.lower():
            return s
    return None
